import type { Metadata } from "next"
import { Inter, Noto_Sans_JP, Fira_Code } from "next/font/google"
import "./globals.css"
import NavBar from '@/components/nav/nav'
import Footer from '@/components/footer'

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"]
})

const notoSansJP = Noto_Sans_JP({
	variable: "--font-noto-sans-jp",
	subsets: ["latin"]
})

const firaCode = Fira_Code({
	variable: "--font-fira-code",
	subsets: ["latin"]
})


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${notoSansJP.variable} ${firaCode.variable} antialiased font-main min-w-screen min-h-screen max-w-screen overflow-x-hidden flex flex-col justify-between`}
			>
				<NavBar />
				<div className="max-w-screen md:p-8 p-6 mb-auto">
					{children}
				</div>
				<Footer />
			</body>
		</html>
	)
}
